config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  root to: 'books#top'

  post 'books' => 'books#create'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice:'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path(book.id), notice:'Book was successfully updated.'
    else
      @book = Book.find(params[:id])
      render :show
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to '/books', notice:'Book was successfully destroyed.'
    else
      @books = Book.all
      render :index
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book, url:book_path) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path %>
<%= link_to "Back", '/books' %>

app/views/books/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>New Book</h3>

<%= render 'layouts/error_messages', model: @book %>

<%= form_for(@book) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<h4>Title:</h4>
<%= @book.title %>
<h4>Body:</h4>
<%= @book.body %>

<br>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', '/books' %>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>

<%= link_to 'start', books_path %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.body %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @product.body %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>